services:
  firebase:
    container_name: firebase
    build:
      context: ./emulators
    ports:
      - 8080:8080 # FIRESTORE_PORT
      - 5005:5005 # FIRESTORE_WS_PORT
      - 4000:4000 # UI_PORT
      - 8085:8085 # PUBSUB_PORT
      - 9099:9099 # AUTH_PORT
